//import { Geist, Geist_Mono } from "next/font/google";

import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import Footer from "@/components/footer/footer";

import {
  ClerkProvider,

} from '@clerk/nextjs'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter=Inter({subsets:["latin"]});
export const metadata = {
  title: "AI Finance Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <Header/>
        <main className="h-screen">{children}</main>
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
