import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutClient from "@/components/LayoutClient/LayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Finance Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <LayoutClient>{children}</LayoutClient> {/* Use client component */}
        </body>
      </html>
    </ClerkProvider>
  );
}
